---
name: gnucashx
description: GnuCashX a cross-platform mobile app for the GnuCash Accounting Software
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.1+1

environment:
  sdk: ">=2.16.1 <3.0.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  archive: ^3.3.0
  uuid: ^3.0.6
  shared_preferences: ^2.0.13
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.1
  provider: ^6.0.2
  dynamic_color: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.0.2
  json_serializable: ^6.2.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  main_locale: en_US
  enabled: true