#!/bin/bash

set -eo pipefail

echo "pre-commit hook: running 'flutter analyze'..."
flutter analyze --fatal-infos --fatal-warnings
echo "pre-commit hook: running 'flutter test'..."
flutter test
echo "pre-commit hook: running 'dart format'..."
dart format .