---
name: Linter

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

on:
  push:
    branches:
      - master
    tags:
      - v* 
  pull_request_target:
    branches: [master, main]

jobs:
  linter:
    name: Lint Code Base 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Disable analytics
        run: flutter config --no-analytics
      
      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Flutter Analyze
        run: flutter analyze --fatal-infos --fatal-warnings