---
name: Pull Request - CI

on:
  pull_request_target:
    paths-ignore:
      - '**.md'
      - 'app/src/main/res/**/strings.xml'
  workflow_dispatch:

jobs:
  test:
    name: Run flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Retrieve dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  build:
    name: Build for Android & Web
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Retrieve dependencies
        run: flutter pub get

      - name: Build apk
        run: flutter build apk

      - name: Build for target appbundle
        run: flutter build appbundle

      - name: Build for target Web
        run: flutter build web

  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    needs: [test]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Retrieve dependencies
        run: flutter pub get

      - name: Build iOS target
        run: flutter build ios --release --no-codesign